name: Deploy Edge Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN  }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      PROJECT_ID: qgxvhncvypeqowyohhys

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase functions deploy --project-ref $PROJECT_ID

      - uses: fjogeleit/http-request-action@v1.14.0
        with:
          url: https://$PROJECT_ID.supabase.co/functions/v1/create-embeddings
          method: POST
          headers: '{"Authorization": "Bearer $SUPABASE_ANON_KEY"}'
          body: '{"name": "Functions"}'
