name: Invoke Generate Embeddings Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  invoke:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: qgxvhncvypeqowyohhys

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: |
          response=$(supabase functions invoke create-embeddings --project-ref $PROJECT_ID --payload '{"name": "World"}')
          echo $response
