name: Call Generate Embeddings Edge Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Call Edge Function
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install @supabase/supabase-js
      - run: node call-edge-function.js
